### ISSUE TITLE
typing exit when done playing results in wrong answer tally to summary of player score

### ISSUE THREAD

**Issue by smokecode** [smokecode/dbc-flashcards#38]

**Comment by smokecode** [comment]
nevermind. my git fetch was acting up. new version is fine.

**Comment by dcr8898** [comment]
There is actually a bug here:  if you immediately exit without answering a card, there is a problem.  This error occurs because I chose not to increment @cards_viewed until an answer was supplied (as opposed to an "exit" command).  I thought this behavior was most accurate, since the user has not attempted to answer, so the card should not be counted against her.  One way to correct this bug is to increment @cards_viewed before requesting the user's response.  But in this case, the user will be "charged" with the current card, even if they then ask to "exit."  This would have the undesirable effect of making a perfect score impossible.

I think the best way to resolve this would be to separate the "game summary" message from the "goodbye" message.  We could always display "goodbye," but only display "game summary" if at least one card is answered.  What do y'all think :question:

**Comment by dcr8898** [comment]
There is actually a bug here:  if you immediately exit without answering a card, there is a problem.  This error occurs because I chose not to increment @cards_viewed until an answer was supplied (as opposed to an "exit" command).  I thought this behavior was most accurate, since the user has not attempted to answer, so the card should not be counted against her.  One way to correct this bug is to increment @cards_viewed before requesting the user's response.  But in this case, the user will be "charged" with the current card, even if they then ask to "exit."  This would have the undesirable effect of making a perfect score impossible.

I think the best way to resolve this would be to separate the "game summary" message from the "goodbye" message.  We could always display "goodbye," but only display "game summary" if at least one card is answered.  What do y'all think :question:

**Comment by smokecode** [comment]
the bug youre talking about, is it the divide by 0 bug? I think I fixed it before reading this issue

**Comment by jeder28** [comment]
The 0 division bug is still there, it says its in view line 26, if you answer 0 questions it can't create the percentage in the end of quiz summary, I can fix.

**Comment by smokecode** [comment]
i already fixed it just pull it down

**Comment by jeder28** [comment]
thanks just saw

**Comment by jeder28** [comment]
@smokecode  nice fix! :sunglasses:
